server:
  port: 9411
  
spring:
  application:
    name: spring-cloud-zipkin
  datasource: 
    url: jdbc:mysql://localhost:3306/spring-cloud-zipkin?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 1987116m
    driver-class-name: com.mysql.jdbc.Driver
#  rabbitmq: 
#    host: localhost
#    port: 5672
#    username: lamic
#    password: lamic
#    virtual-host: lamic_hosts
zipkin: 
  storage: 
    type: mysql
  collector: 
    rabbitmq: 
      addresses: localhost:5672
      password: lamic
      username: lamic
      virtual-host: lamic_hosts
      queue: zipkin
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 30
  instance:
    instanceId: ${spring.application.name}:${random.value}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 15
    lease-expiration-duration-in-seconds: 45